### PR TITLE
Fix wrong number of arguments (given 1, expected 0) (ArgumentError)

### LINKED ISSUE #17: Exception in finalizer
After #15 we started to get: 
```
Exception in finalizer #<Proc:0x0000000108289a20 ...ruby-3.1.0/gems/rb-kqueue-0.2.7/lib/rb-kqueue/watcher/file.rb:45 (lambda)>
...rb-kqueue-0.2.7/lib/rb-kqueue/watcher/file.rb:45:in `block in finalizer': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

We run kqueue like this: 

```
@thread = Thread.new do
  Thread.current.abort_on_exception = true
  queue = KQueue::Queue.new
  queue.watch_file(logfile, :extend) do
      operation_on(file.read)
   end
   queue.run
end
```

when we kill the thread `Thread.kill(@thread)` the exception is raised and since we use `abort_on_exception = true`, this results in crashes in unrelated part of code of other gems.

Most likely we do something weird here, would be happy to hear any suggestions.

### PR DESCRIPTION
**Pull request by dsh2dsh**
like this
```
Exception in finalizer #<Proc:0x0000000108289a20 ...ruby-3.1.0/gems/rb-kqueue-0.2.7/lib/rb-kqueue/watcher/file.rb:45 (lambda)>
...rb-kqueue-0.2.7/lib/rb-kqueue/watcher/file.rb:45:in `block in finalizer': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

According to ri ObjectSpace.define_finalizer:

```
If aProc is a lambda or method, make sure it can be called with a
single argument.
```

Fixes #17

### CODE REVIEW

**Comment by JoeSSS** [comment]
this fixes #17, tested in my environment.

File: lib/rb-kqueue/watcher/file.rb [hunk 1]
```diff
@@ -42,7 +42,7 @@ def initialize(queue, path, flags, callback)
       end
 
       def self.finalizer(fd, path)
-        lambda do
+        lambda do |id|
```
Comment (gregschmit) [inline lib/rb-kqueue/watcher/file.rb:45]: Would this break if this lambda is called with no arguments? I assume so, given that this works in my environment as-is. Perhaps we should have a default value to prevent that case?

```suggestion
        lambda do |id=nil|
```

**Comment by gregschmit** [comment]
This looks good, other than the possible regression I noted. If that works for you, then I'd be happy to merge this and cut a release.

File: lib/rb-kqueue/watcher/file.rb (hunk 1 above)
Comment (dsh2dsh) [reply lib/rb-kqueue/watcher/file.rb]: I've made it optional, thanks.

**Comment by gregschmit** [comment]
Thank you for the submission! Released as `0.2.8`.
